### ISSUE TITLE
List of plants

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/capstone-project#1]
## Value statement (User Story)
As a **user** 
I need **a list of most frequent house plants** 
so that **I can get inspired** 

## Description (Text, Scribble, Wireframe, Design)
![List-of-plants](https://user-images.githubusercontent.com/82395516/120509991-4c3f6d00-c3c9-11eb-905d-01acee1ceecc.png)

## Acceptance criteria
- [ ] Sorted alphabetically ascending

## Tasks
- [ ] Create feature branch
- [ ] Build list item component
- [ ] Write test for component
- [ ] Add list to App
- [ ] Add global styles

## Complexity 
low

**Comment by badabam** [comment]
Did you successfully get some data from the API already?

**Comment by badabam** [comment]
The API is in "alpha" state since 2018. Might be a dead end.
