### ISSUE TITLE
Add pictures

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/capstone-project#2]

**Comment by LisanneArdern** [comment]
## Value statement (User Story)
As a **user** 
I need **a picture to each plant in the list** 
so that **I can identify which plant I have at home or decide which plant I prefer** 

## Description (Text, Scribble, Wireframe, Design)
![Add-pictures](https://user-images.githubusercontent.com/82395516/120513656-c9201600-c3cc-11eb-9058-38897a536fb8.png)



## Acceptance criteria
- [ ] Pictures should match in style
- [ ] Picture should be left from the name of the plant

## Tasks
- [ ] Create feature branch
- [ ] Update list item component
- [ ] Update test for component


## Complexity 
low
