### ISSUE TITLE
Add button to details page linked to favorites pages

### ISSUE THREAD

**Issue by LisanneArdern** [LisanneArdern/capstone-project#24]
## Value statement (User Story)
As a **user** 
I need **a button from that brings me from the details page to the favorites page** 
so that **the user experience improves** 

## Description (Text, Scribble, Wireframe, Design)
![go-to-favorites-button](https://user-images.githubusercontent.com/82395516/129592480-e6adac98-babe-4f58-9c5a-f45657a68182.png)

## Acceptance criteria
- [ ] When clicking on "Go to My Garden" the search will be deleted

## Tasks
- [ ] Create feature branch
- [ ] Update details page
- [ ] Update test

## Complexity 
medium
